### ISSUE TITLE
Staticfile CDN 供应链投毒已被 uBlock Origin 屏蔽，建议移除

### ISSUE THREAD

**Issue by zanxj** [hugo-next/hugo-theme-next#142]
请按照此新功能模版提供相关信息，如详细的功能描述或同类效果屏幕截图，这将有助于我们进行调查。
(Please follow this new feature template to provide relevant information, such as detail description for feature or some screenshots, which will help us investigate.)

## 新功能描述 (New feature description)
**Staticfile CDN** 会随机给文件加料塞广告，被认为是供应链投毒行为，已被 **uBlock Origin** 屏蔽。详见：
https://github.com/uBlockOrigin/uAssets/issues/24292
https://github.com/uBlockOrigin/uAssets/pull/24285

## 效果参考截图 (Screenshots if it possible)
建议把 Staticfile CDN 换成 CloudFlare CDN，详见：
https://cdnjs.cloudflare.com

**Comment by zanxj** [comment]
@elkan1788 更详细曝光 👇
https://www.v2ex.com/t/1057993
https://www.v2ex.com/t/1056428

**Comment by elkan1788** [comment]
感谢你的消息同步，估计投毒行为是有针对性的，暂时看下来是正常的，不过也是给用户增加自已的选择空间，支持加载本地资源（这个整起来真是累人的），也有其他的选择或是自定义CDN服务。
