### ISSUE TITLE
现在无法使用吗？

### ISSUE THREAD

**Issue by SenLief** [hugo-next/hugo-theme-next#2]
构建提示错误
Error: Error building site: TOCSS: failed to transform "main.scss" (text/x-scss): "/home/xxx/blog/themes/hugo-theme-next/assets/css/main.scss:66:25": Invalid CSS after "...ettings_layout:": expected expression (e.g. 1px, bold), was "<no value>;"

hugo v0.101.0 extended

**Comment by elkan1788** [comment]
建议先使用 develop 分支的代码， main 分支还没有正式发布。

**Comment by SenLief** [comment]
好的，这个主题非常不错。
