### ISSUE TITLE
没有config文件夹

### ISSUE THREAD

**Issue by bwcxyk** [hugo-next/hugo-theme-next#4]
exampleSite目录中没有config文件夹

**Comment by elkan1788** [comment]
不明白你的意思，在 exmapleSite 目录下有个 config.yaml 文件作为全局配置文件可用。要是你喜欢使用 config 目录管理，可以参考这个项目： [https://github.com/hugo-next/hugo-next-docs/tree/main/config](https://github.com/hugo-next/hugo-next-docs/tree/main/config)

**Comment by bwcxyk** [comment]
> 不明白你的意思，在 exmapleSite 目录下有个 config.yaml 文件作为全局配置文件可用。要是你喜欢使用 config 目录管理，可以参考这个项目： https://github.com/hugo-next/hugo-next-docs/tree/main/config

现在知道了，把exmapleSite 文件夹内容全复制过去可以了。
