### ISSUE TITLE
livereload.js 在disable livere的情况下不应加载

### ISSUE THREAD

**Issue by finisky** [hugo-next/hugo-theme-next#40]
请按照此 Issue 模版提供相关信息，例如源码仓库、网站链接和屏幕截图，这将有助于我们进行调查。
(Please follow this Issue template to provide relevant information, such as source code repository, website URL and screenshots, which will help us investigate.)

## 问题自检列表 (Issue Checklist)

> 请确认如下情况已检查，并将 [ ] 换成 [x] 来选择 (Change [ ] to [x] to selected which your could make sure)

- [x] 已使用 Hugo Extended 0.86.0 或更高的版本 (I'm using Hugo Extended version 0.86.0 or later)
- [x] 已使用 Hugo NexT 4.0 或更高的版本 (I'm using Hugo NexT version 4.0 or later)
- [x] 已阅读 [Hugo 故障排除](https://gohugo.io/troubleshooting/)并尝试修复无果 (I had already read the [Troubleshooting page of Hugo](https://gohugo.io/troubleshooting/))
- [x] 已搜索过当前所有[已知问题](https://github.com/hugo-next/hugo-theme-next/issues)和[讨论区](https://github.com/hugo-next/hugo-theme-next/discussions/categories/q-a) ，但没有找到帮助 (I had already searched for current [Issues](https://github.com/hugo-next/hugo-theme-next/issues) and [Q & A](https://github.com/hugo-next/hugo-theme-next/discussions/categories/q-a), which does not help me.)

***

## 预期行为 (Expected behavior)

> 请描述你想实现的预期效果 (Please describe the expected behavior what you want)
去掉不必要的livre script

## 实际行为 (Actual behavior)
生成的网站中包括livre头：

<html>
<body>

  | <!DOCTYPE html>
-- | --
  | <html lang="en-us">
  |  
  | <head><script src="/livereload.js?mindelay=10&amp;v=2&amp;port=8903&amp;path=livereload" data-no-instant defer></script><meta charset="UTF-8">
  | <meta name="viewport" content="width=device-width">

</body>
</html>

> 请同时提供网站链接、屏幕截图和源码地址 (Please provide your site links, screenshots and code repository)

## 问题重现步骤 (Steps to reproduce the behavior)
config.yaml中已disable livere，没有相关配置enable

grep了整个repo，并未发现相关js的存在。可能是：`./assets/js/third-party/comments/livere.js`

### 主题配置(Configuration)

> 提供主题 `config.yaml` 中修改过的部分内容 (Paste ONLY CHANGED CONFIGURATION from  `config.yaml`)

```yaml
active: waline
storage: false
```

## 其他有用信息 (Other Information)

> 例如：操作系统、浏览器等 (e.g. Browser, System)

**Comment by elkan1788** [comment]
哈哈，这里不是:bug:，是`Hugo`本地调试时的热加载功能，与 livere 评论组件没有关系

**Comment by finisky** [comment]
原来如此，那这个issue close吧
