### ISSUE TITLE
主页评论数和阅读数的显示

### ISSUE THREAD

**Issue by finisky** [hugo-next/hugo-theme-next#42]
请按照此新功能模版提供相关信息，如详细的功能描述或同类效果屏幕截图，这将有助于我们进行调查。
(Please follow this new feature template to provide relevant information, such as detail description for feature or some screenshots, which will help us investigate.)

## 新功能描述 (New feature description)
主页显示每篇文章的评论数和阅读数，如有性能考虑，可以使用设置选择性开启。

## 效果参考截图 (Screenshots if it possible)
![image](https://user-images.githubusercontent.com/50729876/186717004-4c9fbb04-7c94-4ba9-8446-6ac2447596e7.png)

**Comment by elkan1788** [comment]
虽然是说选择性开启，但也会增加 hugo 判断逻辑影响静态文件生成效率，建议可以考虑通过前端JS判断方式进行动态引入来替代。
