### ISSUE TITLE
rss 支持

### ISSUE THREAD

**Issue by bboysoulcn** [hugo-next/hugo-theme-next#53]
希望提供rss支持

**Comment by elkan1788** [comment]
主题本身就是支持会生成 rss 文件，默认访问路径为： https://你的域名/rss.xml，最终效果参考 [欢迎订阅我的博客](https://lisenhui.cn/rss.xml)。

**Comment by bboysoulcn** [comment]
> 主题本身就是支持会生成 rss 文件，默认访问路径为： [https://你的域名/rss.xml，最终效果参考](https://%E4%BD%A0%E7%9A%84%E5%9F%9F%E5%90%8D/rss.xml%EF%BC%8C%E6%9C%80%E7%BB%88%E6%95%88%E6%9E%9C%E5%8F%82%E8%80%83) [欢迎订阅我的博客](https://lisenhui.cn/rss.xml)。

谢谢
