### ISSUE TITLE
文章浏览数展示出错

### ISSUE THREAD

**Issue by imicky** [hugo-next/hugo-theme-next#74]
请按照此 Issue 模版提供相关信息，例如源码仓库、网站链接和屏幕截图，这将有助于我们进行调查。
(Please follow this Issue template to provide relevant information, such as source code repository, website URL and screenshots, which will help us investigate.)

## 问题自检列表 (Issue Checklist)

> 请确认如下情况已检查，并将 [ ] 换成 [x] 来选择 (Change [ ] to [x] to selected which your could make sure)

- [x] 已使用 Hugo Extended 0.86.0 或更高的版本 (I'm using Hugo Extended version 0.86.0 or later)
- [x] 已使用 Hugo NexT 4.0 或更高的版本 (I'm using Hugo NexT version 4.0 or later)
- [ x 已阅读 [Hugo 故障排除](https://gohugo.io/troubleshooting/)并尝试修复无果 (I had already read the [Troubleshooting page of Hugo](https://gohugo.io/troubleshooting/))
- [x] 已搜索过当前所有[已知问题](https://github.com/hugo-next/hugo-theme-next/issues)和[讨论区](https://github.com/hugo-next/hugo-theme-next/discussions/categories/q-a) ，但没有找到帮助 (I had already searched for current [Issues](https://github.com/hugo-next/hugo-theme-next/issues) and [Q & A](https://github.com/hugo-next/hugo-theme-next/discussions/categories/q-a), which does not help me.)

***

## 预期行为 (Expected behavior)

> 请描述你想实现的预期效果 (Please describe the expected behavior what you want)

**前提：`siteState.statistic.enable=false` （隐藏了侧边栏的站点统计区块）；且 `comments.enable=false`（未开启评论功能）。**

预期：**单篇文章的浏览数，要么所有地方都不显示，要么所有地方都正确显示。**

鉴于侧边栏已经隐藏了浏览量，只需要看单篇文章的浏览数显示，主要在这两类页面：
A、首页单篇文章概要：即 `/` 或 `page/x/`，文章列表中的每一块概要区域，标题处显示的浏览数字。
B、单独文章页：即 `/posts/文章名称.html`，唯一的那个文章标题下方的浏览数字。

## 实际行为 (Actual behavior)

**尝试对以下3个配置项进行true/false改动：**

1. waline.comment
2. waline.pageView
3. analytics.busuanzi.postViews

三项开关排列组合，并观察上述两类页面表现，未能配置出预期效果。

## 问题重现步骤 (Steps to reproduce the behavior)
（站点尚未发布，在本机上测试的）

- A、当 `1:true, 2:true, 3:true` 时：
- - 首页单篇文章概要的浏览数：错误显示为”整站浏览数“
- - 单独文章页内的文章浏览数：符合预期，显示单页浏览数
- B、当 `1:false, 2:false, 3:false` 时：
- - 首页单篇文章概要的浏览数：符合预期，不显示该项
- - 单独文章页内的文章浏览数：错误显示为”loading图标不停转动“
- C、当 `1:true, 2:false, 3:false` 时：
- - 情况与B相同
- D、当 `1:true, 2:false, 3:true` 时：
- - 情况与A相同
- E、当 `1:true, 2:true, 3:false` 时：
- - 首页单篇文章概要的浏览数：错误显示为”loading图标不停转动“
- - 单独文章页内的文章浏览数：错误显示为”loading图标不停转动“
- F、当 `1:false, 2:true, 3:true` 时：
- - 首页单篇文章概要的浏览数：符合预期，不显示该项
- - 单独文章页内的文章浏览数：符合预期，显示单页浏览数
- G、当 `1:false, 2:false, 3:true` 时：
- - 情况与F相同
- H、当 `1:false, 2:true, 3:false` 时：
- - 情况与B相同

唯有`F`的情况才 **勉强符合** 预期，没有明显的错误观感……
这也是根据 `./exampleSite ` 中的 config 文件注释，反复试验多次才做到的。

上述用例 希望对作者有用哈，多谢你的劳动，带来这么酷的主题。

## 环境信息 (Environment Information)

hugo-next theme 分支版本：为 main 当前最新提交 86b9b5a
hugo版本：v0.107.0+extended

## 其他有用信息 (Other Information)

> 例如：操作系统、浏览器等 (e.g. Browser, System)

**Comment by imicky** [comment]
看起来问题主要出现在几个配置项的概念交叉上：

1、waline 作为评论插件却也能提供浏览数，而 busuanzi 也是提供浏览数的，二者在代码上交集的各种 if 判断较为复杂；
2、comments.enable 作为评论功能的总开关，当它关闭时，按说是不是该忽略掉 waline 的相关配置才对？目前它俩的从属关系有些混乱……

**Comment by elkan1788** [comment]
@imicky 你的建议不错，当时考虑到兼容 `hexo-next`主题配置，后续会把文章统计和评论分开来配置，这样也会清晰一些。

> 看起来哥们是做开发的，不知道有没兴趣加入到 hugo-next 主题的开发呢？ 😄
