### ISSUE TITLE
增加层级导航

### ISSUE THREAD

**Issue by hellomyheart** [hugo-next/hugo-theme-next#80]
# 新功能描述 (New feature description)

# 除了全局导航外， 增加层级导航。

在某一层级，支持层级导航覆盖全局导航， 层级导航配置支持多种，
有全局配置， 也有本地配置， 配置有默认路径（同一个文件夹在一个导航内），也可以手动配置（在当前文件夹创建index.config 或者其他方式声明）， 也可以配置Tag（将这个Tag的所有页面配置路径合并为一个导航，排序有更新时间，创建时间， 指定排序字段(在每个文章的开头 --- 内配置)）， 也可以配置类别，一个类别的文章在一起，使用类别筛选/或Tag筛选时，默认本地导航替换全局导航。

全局导航、本地导航 上级导航、下级导航 之间可以配置组合关系，

## 合并（本级合并子级、本级合并上级）

导航和 文章内导航共存， 可以放在左右两边，或者上下两边。

就像书本一样， 在文章内有索引， 子章节有索引， 章节有索引， 有书架（全局导航），里面有很多书

这个功能的另一种实现方式是增加分类和Tag的功能， 分类和Tag可以配置索引规则。 在某一个分类或者Tag页面，可以自定义列表展示样式， 排序等， 使得分类或者Tag有序（多层级）。

如果这两种实现都实现，效果会很好。参考一个博客网站  [这类似于Tag](https://xugaoyi.com/note/javascript/), [这是自定义导航](https://xugaoyi.com/pages/e85e68947502cf90/)

![截图_选择区域_20230103175611](https://user-images.githubusercontent.com/31239692/210334842-bad28d65-83ad-4abe-98e2-6f3833219c72.png)

![截图_选择区域_20230103175559](https://user-images.githubusercontent.com/31239692/210334865-bfba3cb8-b6ad-48a8-a886-db75f7825068.png)

**Comment by elkan1788** [comment]
这个设计会破坏 NexT 主题原本的设计风格，暂不考虑，你可自行调整实现
