### ISSUE TITLE
救命 第一次就编译失败

### ISSUE THREAD

**Issue by Justsenger** [hugo-next/hugo-theme-next#86]
hugo版本：hugo_extended_0.110.0_windows-amd64
执行命令：hugo server

Start building sites …
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended windows/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
ERROR 2023/01/21 20:36:07 render of "taxonomy" failed: "C:\site\saniye.cn\themes\Hugo NexT\layouts\_default\baseof.html:1:21": execute of template failed: template: _default/terms.html:1:21: executing "_default/terms.html" at <partialCached "init.html" .>: error calling partialCached: "C:\site\saniye.cn\themes\Hugo NexT\layouts\partials\init.html:22:14": execute of template failed: template: partials/init.html:22:14: executing "partials/init.html" at <index .Site.Data.resources.vendors $vendor>: error calling index: value is nil; should be of type string
ERROR 2023/01/21 20:36:07 render of "taxonomy" failed: "C:\site\saniye.cn\themes\Hugo NexT\layouts\_default\baseof.html:1:21": execute of template failed: template: _default/terms.html:1:21: executing "_default/terms.html" at <partialCached "init.html" .>: error calling partialCached: "C:\site\saniye.cn\themes\Hugo NexT\layouts\partials\init.html:22:14": execute of template failed: template: partials/init.html:22:14: executing "partials/init.html" at <index .Site.Data.resources.vendors $vendor>: error calling index: value is nil; should be of type string
Error: Error building site: failed to render pages: render of "home" failed: "C:\site\saniye.cn\themes\Hugo NexT\layouts\_default\baseof.html:1:21": execute of template failed: template: index.html:1:21: executing "index.html" at <partialCached "init.html" .>: error calling partialCached: "C:\site\saniye.cn\themes\Hugo NexT\layouts\partials\init.html:22:14": execute of template failed: template: partials/init.html:22:14: executing "partials/init.html" at <index .Site.Data.resources.vendors $vendor>: error calling index: value is nil; should be of type string

**Comment by Justsenger** [comment]
应该直接用项目里的新站点，不要用hugo来建立新站点

**Comment by elkan1788** [comment]
下次这类使用问题可以开到讨论区去，Issue是用来对主题的Bug提出做记录和讨论的。
