### ISSUE TITLE
行内数学公式无法正常显示

### ISSUE THREAD

**Issue by zhenyuxie** [hugo-next/hugo-theme-next#90]
块级公式显示正常，行内公式未正常显示

**md内容：**
$$ E=MC2 $$
$ y=x+10 $

## 问题自检列表 (Issue Checklist)

> 请确认如下情况已检查，并将 [ ] 换成 [x] 来选择 (Change [ ] to [x] to selected which your could make sure)

- [x] 已使用 Hugo Extended 0.86.0 或更高的版本 (I'm using Hugo Extended version 0.86.0 or later)
- [x] 已使用 Hugo NexT 4.0 或更高的版本 (I'm using Hugo NexT version 4.0 or later)
- [x] 已阅读 [Hugo 故障排除](https://gohugo.io/troubleshooting/)并尝试修复无果 (I had already read the [Troubleshooting page of Hugo](https://gohugo.io/troubleshooting/))
- [x] 已搜索过当前所有[已知问题](https://github.com/hugo-next/hugo-theme-next/issues)和[讨论区](https://github.com/hugo-next/hugo-theme-next/discussions/categories/q-a) ，但没有找到帮助 (I had already searched for current [Issues](https://github.com/hugo-next/hugo-theme-next/issues) and [Q & A](https://github.com/hugo-next/hugo-theme-next/discussions/categories/q-a), which does not help me.)

***

## 预期行为 (Expected behavior)

应该正常显示行内公式

## 实际行为 (Actual behavior)

<img width="646" alt="image" src="https://user-images.githubusercontent.com/15904723/219907821-b736c335-a271-43f3-a995-5d1e6f21e590.png">

## 环境信息 (Environment Information)
macbook air m1
chrome浏览器

### 主题配置(Configuration)

> 提供主题 `config.yaml` 中修改过的部分内容 (Paste ONLY CHANGED CONFIGURATION from  `config.yaml`)

```yaml
math: mathjax    
```

## 其他有用信息 (Other Information)
macos
chrome

**Comment by elkan1788** [comment]
貌似 `mathjax` 本身就是不支持行显示，建议可找下 `mathjax` 的相关资料了解下。

**Comment by zhenyuxie** [comment]
> 貌似 `mathjax` 本身就是不支持行显示，建议可找下 `mathjax` 的相关资料了解下。

把 $...$ 替换成 \\(...\\) 解决了，thx

**Comment by zouchanglin** [comment]
可以在header中加入这段代码就好了，直接采用MathJax渲染即可
```html
<script>
  MathJax = {
    tex: {
      inlineMath: [['$', '$'], ['\\(', '\\)']]
    },
    svg: {
      fontCache: 'global'
    }
  };
</script>

<script type="text/javascript" id="MathJax-script" async
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js">
</script>
```

另外，mathjax 本身是支持行内公式的，希望作者可以解决掉这个bug：

```html
<html>
	<head>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML" async></script>

	<!-- <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script> -->
	</head>


	<body>
		<p>二次公式是 $ax^2 + bx + c = 0$其实是支持的行内公式的</p>
		<p>二次公式是 $$ax^2 + bx + c = 0$$</p>

		公式是这样的:$\lim^{x \to \infty}_{y \to 0}{\frac{x}{y}}$ 哈哈哈
	</body>

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    inlineMath: [['$', '$']],
    displayMath: [['$$', '$$']]
  }
});
</script>

</html>
```

**Comment by zouchanglin** [comment]
<img width="1428" alt="image" src="https://github.com/hugo-next/hugo-theme-next/assets/29838710/6371891a-3b57-49cc-bf0f-39e31ac8dea2">

**Comment by elkan1788** [comment]
@zouchanglin 已经修复，现在可以支持行内公式嵌套，可以查看下示例的效果：[数学公式渲染](https://preview.hugo-next.eu.org/demo/math-formula.html#more)
