### ISSUE TITLE
```mermaid 的支持

### ISSUE THREAD

**Issue by turboted** [hugo-next/hugo-theme-next#94]
希望可以支持 ```mermaid  的markdown語法

**Comment by elkan1788** [comment]
Markdown语法并不支持自定义的语法，现在可以直接使用主题已经支持的 `mermaid` 特定短代码，参考示例：https://hugo-next.eu.org/demo/mermaid-charts.html
```
{{< mermaid align="left" >}}

graph TD;

    A-->B;

    A-->C;

    B-->D;

    C-->D;

{{< /mermaid >}}

```

**Comment by turboted** [comment]
可是obsidian 和 typora  都是使用 ```mermaid

**Comment by elkan1788** [comment]
> 可是obsidian 和 typora 都是使用 ```mermaid

这两款是编辑器，它们是自己扩展的呢，不是 markdown 的标准语法。
